# Generated by Django 6.0.5 on 2026-05-16 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='source',
            field=models.CharField(choices=[('people_search', 'People Search'), ('job_signal', 'Job Signal'), ('post_signal', 'Post Signal')], db_index=True, default='people_search', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadDiscovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=20)),
                ('keyword', models.CharField(blank=True, default='', max_length=300)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Discovery',
                'verbose_name_plural': 'Lead Discoveries',
                'indexes': [models.Index(fields=['lead', '-discovered_at'], name='crm_leaddis_lead_id_b5123e_idx')],
            },
        ),
    ]
