# Generated by Django 6.0.5 on 2026-05-16 13:42

from django.db import migrations, models


def drop_legacy_tasks(apps, schema_editor):
    Task = apps.get_model("linkedin", "Task")
    Task.objects.filter(task_type__in=["connect", "check_pending", "follow_up"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='job_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='persona_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(drop_legacy_tasks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('qualify', 'Qualify')], max_length=20),
        ),
    ]
